/**
 * Article page — masthead, footer and the related-entity rail.
 *
 * The page's own markup is generated by tools/intel/publish-intel.mjs, so a
 * crawler is served real content. This script only adds the parts that must be
 * resolved at read time: it turns the article's stored entity IDs into links
 * into the EXISTING directory, using the directory's own URL contract.
 *
 * Every link is built from the directory's route shape, never hardcoded:
 *   facility   /#/facility/<facility id>
 *   doctor     /#/doctor/<dhaUniqueId>
 *   specialty  /?smode=professionals&spec=<label>
 */
const $ = (s, r = document) => r.querySelector(s);
const DATA = '/intelligence/data';

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
const fmt = (iso) => {
  if (!iso) return '';
  const d = new Date(iso);
  return Number.isNaN(d.valueOf()) ? ''
    : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
};

/* Masthead and footer, shared with the landing page. */
$('#intelHeader').outerHTML = `
<header class="intel-mast">
  <div class="intel-mast-in">
    <a class="intel-mark" href="/intelligence/"><b>Doctorna</b><span>Intelligence</span></a>
    <nav aria-label="Sections">
      <a href="/" class="intel-hide-sm">Directory</a>
      <a href="/intelligence/#latest">Latest</a>
      <a href="/intelligence/#research">Research</a>
    </nav>
  </div>
</header>`;
$('#intelFooter').outerHTML = `
<footer class="intel-foot">
  <div class="intel-wrap" style="padding-bottom:0">
    <p style="margin:0">Doctorna Intelligence links to reporting published by its original source.
      <a href="/intelligence/">Back to Intelligence</a> · <a href="/">Healthcare directory</a></p>
  </div>
</footer>`;

/**
 * View count.
 *
 * A static page cannot count anything shared, and localStorage counts one
 * browser rather than the world — presenting either as a view count would be a
 * fabricated statistic. So the figure comes from one of two real places, in
 * order, and from nowhere else:
 *
 *   1. the live counter, when config.json names one (tools/intel/view-endpoint.mjs).
 *      Reading the article registers the view and the server returns the total.
 *   2. views.json, the snapshot taken of that counter when the archive was
 *      published. Read-only: it can display a count, never increment one.
 *
 * With neither available the element stays hidden. No zero, no estimate.
 */
async function showViews(slug) {
  const el = $('.intel-kicker [data-views]');
  if (!el || !slug) return;
  let cfg = {};
  try { cfg = await (await fetch(`${DATA}/config.json`, { cache: 'no-cache' })).json(); } catch { /* optional */ }
  const base = String(cfg.viewEndpoint ?? '').replace(/\/+$/, '');

  const paint = (n) => {
    if (!Number.isFinite(n) || n <= 0) return false;
    el.textContent = `${Number(n).toLocaleString('en-GB')} view${n === 1 ? '' : 's'}`;
    el.hidden = false;
    return true;
  };

  if (base) {
    try {
      const res = await fetch(`${base}/api/intel/view`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ slug }),
      });
      if (res.ok && paint((await res.json()).views)) return;
    } catch { /* fall through to the published snapshot */ }
  }
  try {
    const snap = await (await fetch(`${DATA}/views.json`, { cache: 'no-cache' })).json();
    if (snap?.counted > 0) paint(snap.views?.[slug]);
  } catch { /* no counter has ever run */ }
}

const routes = {
  facility: (id) => `/#/facility/${encodeURIComponent(id)}`,
  doctor: (id) => `/#/doctor/${encodeURIComponent(id)}`,
  specialty: (label) => `/?smode=professionals&spec=${encodeURIComponent(label)}`,
  // The register publishes no location dimension, so nothing is linked here
  // until one exists. See tools/intel/entities.mjs.
  location: () => null,
};

const group = (title, note, items, hrefFor) => {
  if (!items?.length) return '';
  const chips = items.map((e) => {
    const href = hrefFor(e.id ?? e.label, e);
    return href
      ? `<a class="intel-chip" href="${esc(href)}">${esc(e.label)}</a>`
      : `<span class="intel-chip">${esc(e.label)}</span>`;
  }).join('');
  return `<div class="intel-rel-group">
    <p class="intel-rel-label">${esc(title)}</p>
    <div class="intel-chips">${chips}</div>
    ${note ? `<p style="margin:10px 0 0;font-size:12px;color:var(--muted-2)">${esc(note)}</p>` : ''}
  </div>`;
};

async function boot() {
  const host = $('#intelRelated');
  const slug = host?.dataset.slug ?? $('#article')?.dataset.article;
  showViews(slug);
  if (!host?.dataset.slug) return;
  let a;
  try {
    a = await (await fetch(`${DATA}/article-${slug}.json`, { cache: 'no-cache' })).json();
  } catch {
    return; // The static page already carries the article; the rail is additive.
  }

  const rel = a.related ?? {};
  const blocks = [
    group('Related specialties', 'Opens the professional directory filtered to this specialty.',
      rel.specialties, (id) => routes.specialty(id)),
    group('Related facilities', 'Opens the facility profile in the directory.',
      rel.facilities, (id) => routes.facility(id)),
    group('Related professionals', 'Matched only where a full name identifies exactly one professional.',
      rel.doctors, (id) => routes.doctor(id)),
    group('Related locations', null, rel.locations, () => null),
  ].filter(Boolean).join('');

  // Other items from the same story — different outlets, one event.
  let sameStory = '';
  try {
    const idx = await (await fetch(`${DATA}/index.json`, { cache: 'no-cache' })).json();
    const pages = [];
    for (let p = 1; p <= Math.min(idx.pages, 4); p++) {
      pages.push(...(await (await fetch(`${DATA}/page-${p}.json`, { cache: 'no-cache' })).json()).items);
    }
    const related = pages
      .filter((x) => x.slug !== a.slug
        && (x.category === a.category
          || x.specialtyIds?.some((s) => a.specialtyIds?.includes(s))))
      .slice(0, 4);
    if (related.length) {
      sameStory = `<h2 style="margin-top:34px">Related reading</h2>
        <div class="intel-rel-group">
        <div class="intel-grid">${related.map((x) => `
          <article class="intel-item"><a class="intel-link" href="/intelligence/a/${esc(x.slug)}/">
            <span class="intel-kicker"><span class="intel-cat">${esc(x.categoryLabel)}</span></span>
            <h3>${esc(x.title)}</h3>
            <span class="intel-meta"><span class="intel-src">${esc(x.sourceName)}</span>
            ${x.originalPublishedAt ? `<span class="intel-dot"></span><time datetime="${esc(x.originalPublishedAt)}">${esc(fmt(x.originalPublishedAt))}</time>` : ''}</span>
          </a></article>`).join('')}</div></div>`;
    }
  } catch { /* related reading is optional */ }

  // The directory section appears ONLY when there is a directory entity to
  // show. An empty "Connected to Doctorna" heading is worse than no heading:
  // it promises a connection the article does not have. Related reading is a
  // separate section and stands on its own.
  host.innerHTML = (blocks ? `<h2>Connected to the Doctorna directory</h2>${blocks}` : '') + sameStory;
}

boot();
